BEGIN deploy_utils.log_deploy_info('CUSTOM_EXCEPT_HANDLING','custom_except_handling.sql dheltzel'); END;
/

CREATE OR REPLACE FORCE EDITIONING VIEW ADMIN.CUSTOM_EXCEPT_HANDLING (ERR_NUM, PROCNAME, SKIP_ERR, RULE_COMMENT, LOG_TIMESTAMP, USER_NAME) AS 
  select ERR_NUM,PROCNAME,SKIP_ERR,RULE_COMMENT,LOG_TIMESTAMP,USER_NAME from ADMIN.CUSTOM_EXCEPT_HANDLING_;
