BEGIN deploy_utils.log_deploy_info('DATA_AUDIT_LOG','data_audit_log.sql dheltzel'); END;
/

CREATE OR REPLACE FORCE EDITIONING VIEW ADMIN.DATA_AUDIT_LOG (LOG_TIMESTAMP, USER_NAME, EDITION, APP_NAME, TAB_OWNER, TAB_NAME, ACTION_TYPE, DML_TYPE, RECS_AFFECTED, LOG_COMMENT) AS 
  select LOG_TIMESTAMP,USER_NAME,EDITION,APP_NAME,TAB_OWNER,TAB_NAME,ACTION_TYPE,DML_TYPE,RECS_AFFECTED,LOG_COMMENT from ADMIN.DATA_AUDIT_LOG_;
