BEGIN deploy_utils.log_deploy_info('ERR_LOG','err_log.sql dheltzel'); END;
/

CREATE OR REPLACE FORCE EDITIONING VIEW ADMIN.ERR_LOG (TIMESTAMP, USER_NAME, ERROR_TYPE, EDITION, PROC_NAME, ERROR_LOC, ERROR_DATA, SOURCE_FILE, REVISION, REV_AUTHOR, REV_DATE, PLSQL_UNIT, PLSQL_LINE, SQLCODE, SQLERRM, CLIENT_NO, ACCT_NO) AS 
  select TIMESTAMP,USER_NAME,ERROR_TYPE,EDITION,PROC_NAME,ERROR_LOC,ERROR_DATA,SOURCE_FILE,REVISION,REV_AUTHOR,REV_DATE,PLSQL_UNIT,PLSQL_LINE,SQLCODE,SQLERRM,CLIENT_NO,ACCT_NO from ADMIN.ERR_LOG_;
