BEGIN deploy_utils.log_deploy_info('REGISTRYTABLE','registrytable.sql dheltzel'); END;
/

CREATE OR REPLACE FORCE EDITIONING VIEW ADMIN.REGISTRYTABLE (NAMESPACE, ENVIR, NAME, IMMUTABLE, VALUE, CREATE_TS, CREATE_USER, UPDATE_TS, UPDATE_USER) AS 
 select NAMESPACE, ENVIR, NAME, IMMUTABLE, VALUE, CREATE_TS, CREATE_USER, UPDATE_TS, UPDATE_USER from ADMIN.REGISTRYTABLE_;
