-- File action_audit_log.sql
-- Author: dheltzel

CREATE TABLE ACTION_AUDIT_LOG_T
(
  LOG_DATE       DATE DEFAULT ON NULL SYSDATE NOT NULL,
  USER_NAME      VARCHAR2(30) DEFAULT ON NULL USER NOT NULL,
  EDITION        VARCHAR2(30),
  APP_NAME       VARCHAR2(30) NOT NULL,
  ACTION_TYPE    VARCHAR2(30) NOT NULL,
  LOG_COMMENT    VARCHAR2(2000)
)
PARTITION BY RANGE(LOG_DATE) INTERVAL(NUMTOYMINTERVAL(1,'MONTH')) 
(
 PARTITION action_audit_log_2023_10 VALUES LESS THAN (TO_DATE('2023-11-01','YYYY-MM-DD')) 
);

COMMENT ON TABLE ACTION_AUDIT_LOG_T IS 'Auditable actions by any application';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.LOG_DATE IS 'Time that action occured';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.USER_NAME IS 'Login name of the session';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.EDITION IS 'Name of the edition in use, if applicable';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.APP_NAME IS 'Name of the application';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.ACTION_TYPE IS 'User defined type of action';
COMMENT ON COLUMN ACTION_AUDIT_LOG_T.LOG_COMMENT IS 'Description of the action';

CREATE INDEX ACTION_AUDIT_LOG_DATE_IDX ON ACTION_AUDIT_LOG_T (LOG_DATE) LOCAL;
CREATE INDEX ACTION_AUDIT_LOG_TYPE_APP_DATE_IDX ON ACTION_AUDIT_LOG_T (ACTION_TYPE,APP_NAME,LOG_DATE) COMPRESS 2;

CREATE OR REPLACE VIEW ACTION_AUDIT_LOG AS select * from ACTION_AUDIT_LOG_T;
