-- File custom_except_handling.sql
-- Author: dheltzel

CREATE TABLE CUSTOM_EXCEPT_HANDLING_T
(
  ERR_NUM INTEGER NOT NULL,
  PROCNAME VARCHAR2(30) NOT NULL,
  SKIP_ERR VARCHAR2(1),
  RULE_COMMENT VARCHAR2(100),
  CREATE_DATE DATE DEFAULT SYSDATE,
  CREATE_USER VARCHAR2(30) DEFAULT USER,
  UPDATE_DATE DATE DEFAULT SYSDATE,
  UPDATE_USER VARCHAR2(30) DEFAULT USER
);

COMMENT ON TABLE CUSTOM_EXCEPT_HANDLING_T IS 'Dynamic management of exception handling';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.ERR_NUM IS 'The SQL Error this applies to';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.PROCNAME IS 'The name of the calling procedure';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.SKIP_ERR IS 'Y/N - should we skip recording this error?';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.RULE_COMMENT IS 'Comment about why we are suppressing this error';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.CREATE_DATE IS 'When this record was created';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.CREATE_USER IS 'Who created this record';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.MODIFY_DATE IS 'When this record was last updated';
COMMENT ON COLUMN CUSTOM_EXCEPT_HANDLING_T.MODIFY_USER IS 'Who last updated this record';

ALTER TABLE CUSTOM_EXCEPT_HANDLING_T ADD CONSTRAINT CUSTOM_EXCEPT_HANDLING_PK PRIMARY KEY (ERR_NUM, PROCNAME);

CREATE OR REPLACE VIEW CUSTOM_EXCEPT_HANDLING AS select * from CUSTOM_EXCEPT_HANDLING_T;
