-- File data_audit_log.sql
-- Author: dheltzel

CREATE TABLE DATA_AUDIT_LOG_T
(
  LOG_DATE       DATE DEFAULT ON NULL SYSDATE NOT NULL,
  USER_NAME      VARCHAR2(30) DEFAULT ON NULL USER NOT NULL,
  EDITION        VARCHAR2(30),
  APP_NAME       VARCHAR2(30) NOT NULL,
  TAB_OWNER      VARCHAR2(30) NOT NULL,
  TAB_NAME       VARCHAR2(30) NOT NULL,
  ACTION_TYPE    VARCHAR2(30) NOT NULL,
  DML_TYPE       VARCHAR2(30) NOT NULL,
  RECS_AFFECTED  INTEGER NOT NULL,
  LOG_COMMENT    VARCHAR2(2000)
)
PARTITION BY RANGE(LOG_DATE) INTERVAL(NUMTOYMINTERVAL(1,'MONTH')) 
(
 PARTITION data_audit_log_2023_10 VALUES LESS THAN (TO_DATE('2023-11-01','YYYY-MM-DD')) 
);

COMMENT ON TABLE DATA_AUDIT_LOG_T IS 'Auditable DML by any application';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.LOG_DATE IS 'Time that DML occured';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.USER_NAME IS 'Login name of the session';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.EDITION IS 'Edition this process was run in';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.APP_NAME IS 'Name of the process';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.TAB_OWNER IS 'Owner of the affected table';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.TAB_NAME IS 'Name of the affected table';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.ACTION_TYPE IS 'Type of action - Trimming,Migration,Load, etc';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.DML_TYPE IS 'Type of DML - insert, update, delete';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.RECS_AFFECTED IS 'Number of records affected by this process';
COMMENT ON COLUMN DATA_AUDIT_LOG_T.LOG_COMMENT IS 'Comment about the activity';

CREATE INDEX DATA_AUDIT_LOG_DATE_USER_IDX ON DATA_AUDIT_LOG_T (LOG_DATE, USER_NAME) LOCAL;
CREATE INDEX DATA_AUDIT_LOG_DATE_APP_IDX ON DATA_AUDIT_LOG_T (LOG_DATE, APP_NAME) LOCAL;
CREATE INDEX DATA_AUDIT_LOG_DATE_TAB_IDX ON DATA_AUDIT_LOG_T (LOG_DATE, TAB_OWNER, TAB_NAME) LOCAL;

CREATE OR REPLACE VIEW DATA_AUDIT_LOG AS select * from DATA_AUDIT_LOG_T;
