-- File ddl_audit_log.sql
-- Author: dheltzel

CREATE TABLE DDL_AUDIT_LOG_T
(
  LOG_DATE     DATE DEFAULT ON NULL SYSDATE NOT NULL,
  OBJECT_OWNER VARCHAR2(30) NOT NULL,
  OBJECT_NAME  VARCHAR2(30) NOT NULL,
  OBJECT_TYPE  VARCHAR2(30) NOT NULL,
  PARENT_NAME  VARCHAR2(30),
  TICKET       VARCHAR2(30),
  SQL_EXECUTED VARCHAR2(4000) NOT NULL,
  USER_NAME    VARCHAR2(30) DEFAULT ON NULL USER NOT NULL,
  EDITION      VARCHAR2(30),
  SOURCE_FILE  VARCHAR2(30),
  REVISION     VARCHAR2(30),
  REV_AUTHOR   VARCHAR2(30),
  REV_DATE     VARCHAR2(30),
  SQLCODE      VARCHAR2(30),
  MESSAGE      VARCHAR2(4000),
  ROLLBACK_DDL VARCHAR2(4000)
)
PARTITION BY RANGE(LOG_DATE) INTERVAL(NUMTOYMINTERVAL(1,'MONTH')) 
(
 PARTITION ddl_audit_log_2023_10 VALUES LESS THAN (TO_DATE('2023-11-01','YYYY-MM-DD')) 
);

COMMENT ON TABLE DDL_AUDIT_LOG_T IS 'DDL Changes';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.LOG_DATE IS 'Time that DDL change was executed';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.OBJECT_OWNER IS 'Owner of the object that was changed';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.OBJECT_NAME IS 'Name of the object that was changed';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.OBJECT_TYPE IS 'Type of the object that was changed';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.PARENT_NAME IS 'Name of the objects parent - if applicable';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.TICKET IS 'Ticket associated with this change';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.SQL_EXECUTED IS 'Actual SQL that was run for this DDL change';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.EDITION IS 'Name of the edition the executing session is using';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.SQLCODE IS 'Value of SQLCODE'; 
COMMENT ON COLUMN DDL_AUDIT_LOG_T.USER_NAME IS 'Login name of the session';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.SOURCE_FILE IS 'URL of the source file';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.REVISION IS 'File Revision info';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.REV_AUTHOR IS 'Author of the last change';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.REV_DATE IS 'Time of the last change';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.MESSAGE IS 'Comment - ex. value of SQLERRM';
COMMENT ON COLUMN DDL_AUDIT_LOG_T.ROLLBACK_DDL IS 'DDL to rollback this change';

CREATE INDEX DDL_AUDIT_LOG_DATE_REVISION_IDX ON DDL_AUDIT_LOG_T (LOG_DATE, REVISION) LOCAL;

CREATE OR REPLACE VIEW DDL_AUDIT_LOG AS select * from DDL_AUDIT_LOG_T;
